# Operasi dan Komputasi Array dengan NumPy

Setelah kita memahami apa dan bagaimana array dalam NumPy bisa membantu kita merepresentasikan sekumpulan nilai atau data, saatnya untuk menerapkan beberapa operasi dan manipulasi array dengan array.

In [ ]:
import numpy as np

## Manipulasi Array

Manipulasi array adalah babagimana sebuah array dapat diubah bentuk dan representasinya ke dalam bentuk dan representasi lain. Misalkan kita definisikan array 1D dan 2D seperti pada potongan kode di bawah.

```python
array2d = np.array([[1, 2, 4], [2, 4, 8], [3, 6, 18], [4, 16, 32]])
array3d = np.array([[[.1, .4], [.2, .5], [.3, .6]], [[.7, 1.], [.8, 1.1], [.9, 1.2]]])
```

NumPy menyediakan fungsi dan metode bawaan untuk melakukan beberapa manipulasi array yang meliputi:
* Mengubah dimensi atau ukuran array
* Meratakan array multidimensi menjadi 1D yang panjang
* Melakukan tranpose
* Menggabungkan beberapa array menjadi satu
* dan lainya

In [ ]:
array2d = np.array([[1, 2, 4], [2, 4, 8], [3, 6, 18], [4, 16, 32]])
array3d = np.array([[[.1, .4], [.2, .5], [.3, .6]], [[.7, 1.], [.8, 1.1], [.9, 1.2]]])

print(array2d)
print(array3d)

[[ 1  2  4]
 [ 2  4  8]
 [ 3  6 18]
 [ 4 16 32]]
[[[0.1 0.4]
  [0.2 0.5]
  [0.3 0.6]]

 [[0.7 1. ]
  [0.8 1.1]
  [0.9 1.2]]]


### Mengubah Dimensi Array

Mengubah dimensi suatu array dapat dilakukan dengan 2 cara:
* menggunakan fungsi
* menggunakan metode array

Hampir semua fungsi yang digunakan untuk mengubah dimensi memiliki padanan metode, sehingga akan lebih singkat dalam mengetik. Beberapa fungsi dengan tujuan ini seperti `numpy.reshape`, `numpy.tranpose`, `numpy.squeeze`, dan `numpy.expand_dims`.

`numpy.reshape` akan mengubah dimensi array masukan `a` mejadi dimensi baru `newshape` yang kita beri. Perlu diperhatikan bahwa dimensi baru yang diminta haruslah kompatibel dengan ukuran aslinya, alias jumlah elemen yang ada di dalam suatu array harus selalu sama. Sebagai contoh, mari kita coba kode di bawah ini yang mengubah ukuran `array2d` dan `array3d`.

In [ ]:
print("old shape:", array2d.shape)
print(array2d)
array2d_new = np.reshape(array2d, (2, 6))
print("new shape:", array2d_new.shape)
print(array2d_new)

In [ ]:
print("old shape:", array3d.shape)
print(array3d)
array3d_new = np.reshape(array3d, (4, 3))
print("new shape:", array3d_new.shape)
print(array3d_new)

Jika kita memaksa untuk mengubah dimensi array ke dimensi yang baru yang jumlah elemennya lebih kecil ataupu besar, maka kita akan mendapatkan `ValueError`. Misalkan kita ingin mengubah `array2d` menjadi array berdimensi `(5, 3)`. Maka kita akan mendapatkan `ValueError`.

Selain dengan fungsi `numpy.reshape`, NumPy juga menyediakan metode `ndarray.reshape` yang ekuivalen dengan `numpy.reshape`.

In [ ]:
array3d.reshape((4, 3))

`numpy.transpose`, sesuai namanya, akan melakukan operasi *transpose*, yaitu mengubah dimensi array dari yang awalnya berukuran `(n, m)` menjadi `(m, n)`. Untuk array multidimensi, jika tidak diberikan urutan dimensi yang baru, maka urutan dimensi akan dibalik. Misalkan dari yang awalnya berukuran `(n, m, l, k)` menjadi `(k, l, m, n)`. Akan tetapi, jika argumen untuk parameter `axes` kita berikan, maka dimensi awal akan disusun ulang (permutasi) berdasarkan urutan indeks pada `axes`.

In [ ]:
np.transpose(array2d)

NameError: name 'np' is not defined

In [ ]:
np.transpose(array2d, axes=(1, 0))

In [ ]:
np.transpose(array3d)

In [ ]:
np.transpose(array3d, axes=(0, 2, 1))

Selain dengan fungsi `numpy.tranpose`, kita juga bisa melakukan hal yang sama dengan metode `ndarray.transpose` atau `ndarray.T`. Khusus untuk `ndarray.T`, array yang dihasilkan hanyalah menukar dimensi pertama dengan dimensi terakhir array.

In [ ]:
array2d.transpose()

In [ ]:
array3d.transpose()

In [ ]:
array3d.T

In [ ]:
array3d.transpose(1, 2, 0)

In [ ]:
array3d.transpose(1, 2, 0)

`numpy.squeeze` akan mengubah dimensi dengan menghapus dimensi dengan panjang **1**. Sebagai contoh, misalkan suatu array memiliki dimensi `(1, 3, 1)`, `numpy.squeeze` akan menghilangkan dimensi pertama (`0`) dan ketiga (`2`) yang jumlah elemennya 1, sehingga array tersebut akan berdimensi `(3,)`.

Selain itu, kita juga bisa memilih dimensi (*axis*) mana yang akan kita hilangkan. *Axis* yang kita pilih harus memenuhi syarat jumlah elemennya harus 1. Jika tidak, kita akan mendapat `ValueError`.

In [ ]:
rng = np.random.default_rng(11)

array_131 = rng.integers(10, size=(1, 3, 1))
array_212 = np.array([[[1, 2]], [[1, 2]]])
array_11 = np.array([[10]])
print(array_131, array_131.shape)
print(array_11, array_11.shape)
print(array_212, array_212.shape

In [ ]:
array_3 = np.squeeze(array_131)
print(array_3, array_3.shape)

array_13 = np.squeeze(array_131, axis=-1)
print(array_13, array_13.shape)

In [ ]:
array_22 = np.squeeze(array_212)
print(array_22, array_22.shape)

In [ ]:
array_0 = np.squeeze(array_11)
print(array_0, array_0.shape)
print(array_0.item())
print(array_0[()])

Kebalikan dari `numpy.squeeze`, `numpy.expand_dims` mengubah dimensi suatu array dengan menambah dimensi baru pada *axis* atau dimensi yang kita sediakan pada fungsi `expand_dims`. Dimensi baru yang ditambahkan adalah dimensi minimal yang dibutuhkan untuk menambah jumlah dimensi, yaitu `1`. Sehingga, jika kita menerapkan `expand_dims` untuk array berdimensi `nxm` dengan memasukkan argumen `axis=1`, akan berubah dimensinya menjadi `nx1xm`.

In [ ]:
print(array2d, array2d.shape)
print(array3d, array3d.shape)

In [ ]:
np.expand_dims(array2d, axis=1)    # (4, 1, 3)

In [ ]:
np.expand_dims(array2d, axis=(1, -1))    # (4, 1, 3, 1)

Selain menggunakan `numpy.expand_dims`, alternatif lain untuk "memperluas" dimensi array adalah dengan menggunakan *indexing* khusus. *Indexing* yang dimaksud adalah *indexing* yang menggunakan objek `None` dan `np.newaxis`. Ketika kita menambahkan objek tersebut pada ***axis* yang kosong** saat *indexing*, maka *axis* tersebut akan menjadi dimensi baru dengan jumlah elemen sama dengan 1.

> [`numpy.newaxis`](https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis) bisa dibilang sebuah alias dari `None`.

In [ ]:
array2d[None, :]    # (1, 4, 3)

In [ ]:
array2d[np.newaxis, :]    # (1, 4, 3)

In [ ]:
array2d[:, None, :, None]    # (4, 1, 3, 1)

> **Tugas Eksplorasi**
>
> Cobalah beberapa fungsi untuk mengubah dimensi array yang lainnya di bawah ini, seperti:
> * `ndarray.flat`
> * `ndarray.flatten`
> * `numpy.ravel`

### Penggabungan Array

Sering kali kita memiliki beberapa array yang merepresentasikan beberapa data yang berbeda dan perlu digabungkan untuk pemrosesan selanjutnya. NumPy menyediakan utilitas untuk melakukan hal tersebut seperti `numpy.concatenate`.

`numpy.concatenate` akan menggabungkan sekumpulan array sepanjang **axis** yang kita sediakan. Jika kita ingin menggabungkan sekumpulan array pada dimensi pertamanya, maka kita tidak perlu menyediakan *axis* karena nilai default *axis* adalah 0.

In [ ]:
x = rng.integers(10, size=(2, 5))
y = rng.integers(10, 20, size=(3, 5))
z = rng.integers(20, 30, size=(3, 3))

print(x, x.shape)
print(y, y.shape)
print(z, z.shape)

In [ ]:
np.concatenate([x, y])    # (5, 5)

Array yang akan digabungkan harus memiliki **dimensi yang sama, kecuali pada dimensi yang sesuai dengan *axis* yang dipilih**. Jika tidak, maka kita akan mendapatkan eror yang serupa seperti di bawah ini

```python
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension ..., the array at index ... has size ... and the array at index ... has size ...
```

In [ ]:
np.concatenate([y, z, y], axis=-1)    # (3, 13)

In [ ]:
np.concatenate([np.resize(x, (5, 3)), z])

> **Tugas Eksplorasi**
>
> Eksplor dan coba beberapa fungsi lain seperti `numpy.append`, `numpy.hstack`, dan `numpy.vstack`. Lalu, jawab dan lakukan pertanyaan berikut:
> 1. Apa perbedaan ketiganya?
> 2. Apa perbedaan antara `numpy.hstack` dan `numpy.vstack` dengan `numpy.concatenate`?
> 3. Demokan ketiga fungsi tersebut menggunakan array `x`, `y`, dan `z`!

## Operasi Aritmatika dengan NumPy

Salah satu kelebihan array dibanding list adalah implementasi operasi aritmatika yang melibatkan skalar, vektor, matirks, dan bahkan array n-dimensi yang efektif. Bahkan, beberapa fungsi dalam NumPy yang berurusan dengan operasi aljabar menggunakan versi bahasa pemrograman C sehingga operasi bisa lebih cepat.

### *Broadcasting*

*Broadcasting* merupakan salah satu teknik yang dilakukan oleh NumPy untuk memperlakukan array yang berbeda ukuran saat operasi aritmatika. Secara umum, array yang berdimensi lebih "kecil" akan "disebarkan" (*broadcast*) mengikuti array yang berdimensi lebih "besar" sedemikian hingga kedua array memiliki ukuran yang sama dan kompatibel untuk dilakukan operasi.

<div align="middle">
<img src="../../assets/gif/broadcast.gif">
</div>

### Penjumlahan

Secara umum, operasi penjumlahan array dapat dilakukan menggunakan operator `+`, baik itu skalar, vektor, ataupun array n-dimensi.

#### Penjumlahan Vektor dengan Skalar

Penjumlahan vektor dengan skalar memanfaatkan *broadcasting* yang membuat operan skalar disebar untuk setiap elemen pada vektor seperti yang ditunjukkan pada ilustrasi di atas. Vektor yang dimaksud di sini adalah array dengan ukuran `(n,)`, `(1, n)`, atau `(n, 1)`.

In [ ]:
a = 2
b = 1.5
c = 10

x = np.array([5, 10, 15])
y = x[None, :]
z = x[:, None]

print(x.shape)
print(y.shape)
print(z.shape)

In [ ]:
print(x + a)
print(y + b)
print(z + c)

#### Penjumlahan Vektor - Matriks dan Antar Matriks

Penjumlahan vektor dengan vektor juga menggunakan operator `+` dan memanfaatkan fitur *broadcasting* NumPy.

In [ ]:
x + x

In [ ]:
x + y

In [ ]:
x + z

In [ ]:
y + z

Penjumlahan vektor dan matriks juga memanfaatkan *broadcasting* di mana vektor akan direntangkan untuk mengikuti ukuran suatu matriks. Syarat agar operasi ini dapat dilakukan adalah salah satu *axis* antara vektor dan matriks harus sama. Ekspresi `x + z` merupakan salah satu contoh penjumlahan vektor dengan matriks, di mana `x` adalah vektor, dan `z` adalah matriks atau array 2-dimensi.

In [ ]:
xx = np.resize(x, (4, x.shape[0]))
print(xx)

In [ ]:
x + xx

In [ ]:
xx + y

In [ ]:
xx[:, None] + z

> **Kuis:**
>
> Coba jelaskan dan demokan bagaimana ekspresi `xx[:, None] + z` bisa dijalankan dan kenapa `xx + z` tidak kompatibel!

Penjumlahan antar matriks mengikuti aturan pada aljabar di mana ukuran matriks harus sama. *Broadcasting* hanya akan dipakai ketika kita ingin menjumlahkan matriks dengan ukuran yang berbeda dan menambah dimensi baru pada salah satu atau kedua matriks.

> Operasi pengurangan dan pembagian berperilaku sama dengan operasi penjumlahan, mulai dari ekspresi yang menggunakan operator `-` dan `/` secara berturut-turut untuk pengurangan dan pembagian, aturan *broadcasting*, dan operasi vektor-matriks.

In [ ]:
m = np.arange(12).reshape(4, 3)
print(m)

In [ ]:
xx + m

### Perkalian

Berbeda dengan penjumlahan di atas, ada beberapa cara untuk melakukan operasi perkalian. Setiap cara berperilaku dan menghasilkan hasil yang berbeda.

#### Perkalian Pada Elemen Array

Perkalian vektor dengan skalar dan juga matriks dengan skalar akan mengalikan setiap elemen pada vektor/matriks dengan skalar atau yang disebut dengan *element-wise multiplication*. Untuk melakukan ini, kita bisa menggunakan operator `*`.

In [ ]:
d = 10
print(x * d)
print(y * d)
print(z * d)
print(xx * d)
print(array3d * d)

Selain dengan operator `*`, NumPy menyediakan fungsi untuk melakukan hal serupa, yaitu `numpy.multiply`. Untuk melakukan ini, syaratnya adalah kedua array harus berukuran sama atau jika tidak sama, paling tidak bisa dilakukan *broadcasting*.

In [ ]:
print(np.multiply(x, d))
print(np.multiply(xx, d))

In [ ]:
print(np.multiply(xx, y))
print(np.multiply(y, z))

#### Perkalian Matriks

Ingat bahwa, perkalian antar matriks hanya bisa dilakukan jika dan hanya jika kolom pada matriks pertama sama dengan baris pada matriks kedua. Ini juga berlaku dalam NumPy, yang menggunakan `numpy.dot` untuk melakukan perkalian matriks, atau secara umum *dot/inner product*.

In [ ]:
np.dot(xx, xx.T)

In [ ]:
np.dot(y, z)

In [ ]:
np.dot(z, y)

**Eksplorasi**:
* https://numpy.org/doc/stable/user/quickstart.html
* https://numpy.org/doc/stable/user/absolute_beginners.html

## Mentoring

In [ ]:
import numpy as np

In [ ]:
array3d = np.full((2, 1, 3), 3)
array2d = np.full((3, 3), 5)

print(array3d, array3d.shape)
print(array2d, array2d.shape)

[[[3 3 3]]

 [[3 3 3]]] (2, 1, 3)
[[5 5 5]
 [5 5 5]
 [5 5 5]] (3, 3)


In [ ]:
np.concatenate([array2d[:, None], array3d], axis=-1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
array3d

array([[[0.1, 0.4],
        [0.2, 0.5],
        [0.3, 0.6]],

       [[0.7, 1. ],
        [0.8, 1.1],
        [0.9, 1.2]]])

In [ ]:
array3d[0]

array([[0.1, 0.4],
       [0.2, 0.5],
       [0.3, 0.6]])

In [ ]:
array3d[:, 0, :]

array([[0.1, 0.4],
       [0.7, 1. ]])

In [ ]:
array3d[0], array3d[0].shape

(array([[0.1, 0.4],
        [0.2, 0.5],
        [0.3, 0.6]]),
 (3, 2))

In [ ]:
array3d[:, 0], array3d[:, 0].shape

(array([[0.1, 0.4],
        [0.7, 1. ]]),
 (2, 2))

In [ ]:
array3d[:, :, 0], array3d[:, :, 0].shape

(array([[0.1, 0.2, 0.3],
        [0.7, 0.8, 0.9]]),
 (2, 3))

In [ ]:
array3d[:, :, 1], array3d[:, :, 1].shape

(array([[0.4, 0.5, 0.6],
        [1. , 1.1, 1.2]]),
 (2, 3))

In [ ]:
test = np.transpose(array3d, axes=(2, 0, 1))
print(test)
print(test.shape)

[[[0.1 0.2 0.3]
  [0.7 0.8 0.9]]

 [[0.4 0.5 0.6]
  [1.  1.1 1.2]]]
(2, 2, 3)


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=755892f1-a617-4a5f-868e-ec54428f8e09' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>